I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 23, in script
    with dissolve(2)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 23, in script
    with dissolve(2)
  File "C:\Users\WazX\Downloads\Common Software\Ren'Py\renpy-6.99.13-sdk\renpy\ast.py", line 1289, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\WazX\Downloads\Common Software\Ren'Py\renpy-6.99.13-sdk\renpy\exports.py", line 1406, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\WazX\Downloads\Common Software\Ren'Py\renpy-6.99.13-sdk\renpy\display\core.py", line 2123, in do_with
    clear=clear)
  File "C:\Users\WazX\Downloads\Common Software\Ren'Py\renpy-6.99.13-sdk\renpy\display\core.py", line 2553, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\WazX\Downloads\Common Software\Ren'Py\renpy-6.99.13-sdk\renpy\display\core.py", line 2774, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
Ryuka Bully 1.0
